# Generated by Django 4.2.2 on 2023-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_alive', models.BooleanField(default=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
