# Generated by Django 4.2.2 on 2023-06-12 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_playercontact_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercontact',
            name='action',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playercontact',
            name='new_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playercontact',
            name='telephone',
            field=models.CharField(default=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Le format du téléphone n'est pas le bon...", regex='^\\+?1?\\d{9,11}$')]),
            preserve_default=False,
        ),
    ]
