# Generated by Django 4.2.2 on 2023-06-12 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_playercontact_action_playercontact_new_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercontact',
            name='new_field',
        ),
        migrations.RemoveField(
            model_name='playercontact',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Le format du téléphone n'est pas le bon...", regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
