# Generated by Django 4.2.2 on 2023-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_playercontact_new_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercontact',
            name='target',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
