# Generated by Django 4.2.2 on 2023-06-12 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_playercontact_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercontact',
            name='telephone',
            field=models.CharField(default=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Le format du téléphone n'est pas le bon...", regex='^\\+?1?\\d{9,11}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
