# Generated by Django 4.2.2 on 2023-06-12 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_playercontact_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercontact',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Le format du téléphone n'est pas le bon...", regex='^\\+33\\d{9}$')]),
        ),
    ]
