# Generated by Django 4.2.2 on 2023-06-14 10:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_playercontact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
