# Generated by Django 4.2.2 on 2023-06-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercontact',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.games'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
