# Generated by Django 4.2.2 on 2023-06-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_playercontact_game_delete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercontact',
            name='game',
        ),
        migrations.AddField(
            model_name='games',
            name='players',
            field=models.ManyToManyField(to='info.playercontact'),
        ),
    ]
