# Generated by Django 4.2.2 on 2023-07-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_remove_playercontact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='status',
        ),
        migrations.AddField(
            model_name='games',
            name='mode',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
