# Generated by Django 4.2.2 on 2023-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_alter_games_gamemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercontact',
            name='player_email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
    ]
