# Generated by Django 4.2.2 on 2023-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_alter_playercontact_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercontact',
            name='action',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='player_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='playercontact',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
